import { Component } from '@angular/core';
import {
  FormBillingComponent,
  FormCartComponent,
  FormCheckoutSummaryComponent,
  FormDeleteAccountComponent,
  FormFeedbackComponent,
  FormFilterComponent,
  FormLoginComponent,
  FormLoginTabsComponent,
  FormNewsletterComponent,
  FormNotificationsComponent,
  FormPaymentComponent,
  FormProfileSettingsComponent,
  FormReviewComponent,
  FormShippingComponent,
  FormSignupComponent,
  FormSignupTabsComponent,
  FormSuccessMessageComponent,
  FormTeamInviteComponent,
  FormWizardComponent,
} from 'Base';
import { ShowcasePage, ShowcaseNavSection } from '../showcase-page';
import { ShowcaseSection } from '../showcase-section';

@Component({
  selector: 'app-ui-form-blocks',
  imports: [
    ShowcasePage,
    ShowcaseSection,
    FormBillingComponent,
    FormNotificationsComponent,
    FormFeedbackComponent,
    FormWizardComponent,
    FormTeamInviteComponent,
    FormCartComponent,
    FormCheckoutSummaryComponent,
    FormDeleteAccountComponent,
    FormFilterComponent,
    FormLoginComponent,
    FormLoginTabsComponent,
    FormNewsletterComponent,
    FormPaymentComponent,
    FormProfileSettingsComponent,
    FormReviewComponent,
    FormShippingComponent,
    FormSignupComponent,
    FormSignupTabsComponent,
    FormSuccessMessageComponent,
  ],
  templateUrl: './form-blocks.html',
})
export class UiFormBlocks {
  protected readonly sections: ShowcaseNavSection[] = [
    { id: 'billing', label: 'Billing' },
    { id: 'payment', label: 'Payment' },
    { id: 'shipping', label: 'Shipping' },
    { id: 'cart', label: 'Cart' },
    { id: 'checkout', label: 'Checkout summary' },
    { id: 'notifications', label: 'Notifications' },
    { id: 'feedback', label: 'Feedback' },
    { id: 'review', label: 'Review' },
    { id: 'newsletter', label: 'Newsletter' },
    { id: 'team-invite', label: 'Team invite' },
    { id: 'filter', label: 'Filter' },
    { id: 'login', label: 'Login' },
    { id: 'signup', label: 'Signup' },
    { id: 'login-tabs', label: 'Login tabs' },
    { id: 'signup-tabs', label: 'Signup tabs' },
    { id: 'profile-settings', label: 'Profile settings' },
    { id: 'wizard', label: 'Wizard' },
    { id: 'success', label: 'Success message' },
    { id: 'delete-account', label: 'Delete account' },
  ];
}
